In [66]:
# Import lib

import pandas as pd
import os

In [67]:
# Load the datasets

air_df = pd.read_csv('data/hcm_air_data.csv')

weather_df = pd.read_csv('data/hcmc_weather_data.csv')

In [68]:
# Convert to datetime objects

air_df['datetime_local'] = pd.to_datetime(air_df['datetime_local'])

weather_df['time'] = pd.to_datetime(weather_df['time'])

In [69]:
# Remove the timezone

air_df['datetime_local_naive'] = air_df['datetime_local'].dt.tz_localize(None)

In [70]:
# Merge the datasets

df = pd.merge(
    air_df, 
    weather_df, 
    left_on='datetime_local_naive', 
    right_on='time', 
    how='left'
)

In [71]:
# Clean up

df = df.drop(columns=['datetime_local_naive', 'time'])

df = df.sort_values(by='datetime_local').reset_index(drop=True)

In [72]:
df = df.set_index('datetime_local')

In [73]:
df.shape

(9418, 14)

In [74]:
df.head()

,pm1,pm10,pm25,relativehumidity,temperature,um003,temperature_2m,relative_humidity_2m,precipitation,surface_pressure,wind_speed_10m,wind_direction_10m,temperature_180m,boundary_layer_height
datetime_local,,,,,,,,,,,,,,
2024-11-19 18:00:00+07:00,18.600000,33.040001,29.139999,62.800000,27.172000,3519.660059,30.9,59,0.1,1007.6,1.0,211,NaN,150.0
2024-11-19 19:00:00+07:00,18.700000,32.650000,29.150000,57.816667,29.025001,3363.499980,29.3,68,0.0,1008.4,4.9,204,NaN,245.0
2024-11-19 20:00:00+07:00,20.533333,36.199999,31.783333,57.333333,29.130000,3903.650004,26.6,77,0.2,1009.5,2.8,105,NaN,95.0
2024-11-19 21:00:00+07:00,20.016667,34.383333,30.950000,56.883334,29.161667,3583.299988,26.6,79,0.1,1010.0,4.0,309,NaN,85.0
2024-11-19 22:00:00+07:00,19.679167,33.304167,30.216667,56.395833,29.043750,3495.024984,26.8,79,0.0,1009.9,3.2,164,NaN,55.0

In [75]:
df.tail()

,pm1,pm10,pm25,relativehumidity,temperature,um003,temperature_2m,relative_humidity_2m,precipitation,surface_pressure,wind_speed_10m,wind_direction_10m,temperature_180m,boundary_layer_height
datetime_local,,,,,,,,,,,,,,
2026-02-09 20:00:00+07:00,19.727667,NaN,29.700167,51.657167,28.217000,3614.441667,27.5,68,0.0,1011.3,9.8,175,NaN,255.0
2026-02-09 21:00:00+07:00,18.316500,NaN,28.180667,51.946167,27.950167,3253.491667,26.5,73,0.0,1011.8,7.4,176,NaN,240.0
2026-02-09 22:00:00+07:00,18.047167,NaN,27.502500,53.149000,27.819000,3132.941667,26.0,75,0.0,1011.5,7.5,153,NaN,220.0
2026-02-09 23:00:00+07:00,17.376292,NaN,26.528375,58.122417,27.507417,3027.941667,25.6,75,0.0,1011.5,6.3,156,NaN,220.0
2026-02-10 00:00:00+07:00,18.899636,NaN,28.966727,59.368000,27.109273,3317.563636,25.4,76,0.0,1011.4,2.5,360,NaN,250.0

In [76]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9418 entries, 2024-11-19 18:00:00+07:00 to 2026-02-10 00:00:00+07:00
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   pm1                    9418 non-null   float64
 1   pm10                   1261 non-null   float64
 2   pm25                   9418 non-null   float64
 3   relativehumidity       9418 non-null   float64
 4   temperature            9418 non-null   float64
 5   um003                  9418 non-null   float64
 6   temperature_2m         9418 non-null   float64
 7   relative_humidity_2m   9418 non-null   int64
 8   precipitation          9418 non-null   float64
 9   surface_pressure       9418 non-null   float64
 10  wind_speed_10m         9418 non-null   float64
 11  wind_direction_10m     9418 non-null   int64
 12  temperature_180m       0 non-null      float64
 13  boundary_layer_height  9418 non-null   float64
dtypes: float64(12), int64(2)
memory usage: 1.1 MB

In [77]:
df.describe()

,pm1,pm10,pm25,relativehumidity,temperature,um003,temperature_2m,relative_humidity_2m,precipitation,surface_pressure,wind_speed_10m,wind_direction_10m,temperature_180m,boundary_layer_height
count,9418.000000,1261.000000,9418.000000,9418.000000,9418.000000,9418.000000,9418.000000,9418.000000,9418.000000,9418.000000,9418.000000,9418.000000,0.0,9418.000000
mean,23.302627,47.056177,34.925634,53.512119,28.994170,4866.079826,27.332013,77.984922,0.270684,1008.996921,6.782587,187.406987,NaN,535.015927
std,10.866156,22.619559,17.386305,8.383953,2.273432,2949.673377,3.091986,16.734234,1.106731,2.450194,3.599558,99.622624,NaN,504.516372
min,1.966875,5.394125,2.916958,22.202500,23.032500,535.108333,17.900000,22.000000,0.000000,1001.800000,0.000000,1.000000,NaN,10.000000
25%,15.944740,28.630042,23.094344,48.128573,27.544125,2810.698428,25.000000,68.000000,0.000000,1007.300000,4.000000,119.000000,NaN,155.000000
50%,21.663729,45.623167,32.149396,54.171729,28.533729,4016.126068,26.600000,82.000000,0.000000,1008.900000,6.300000,187.000000,NaN,360.000000
75%,28.288635,62.864125,42.809802,59.507469,29.966534,6050.301607,29.400000,92.000000,0.100000,1010.600000,9.000000,261.000000,NaN,750.000000
max,104.343749,181.028334,171.267000,74.114181,42.794500,25015.039551,37.300000,100.000000,18.800000,1017.100000,23.400000,360.000000,NaN,2800.000000

In [78]:
df.nunique()

pm1                      9400
pm10                     1261
pm25                     9413
relativehumidity         9391
temperature              9375
um003                    9415
temperature_2m            182
relative_humidity_2m       79
precipitation             113
surface_pressure          151
wind_speed_10m            203
wind_direction_10m        360
temperature_180m            0
boundary_layer_height     475
dtype: int64

In [79]:
df.isnull().sum()

pm1                         0
pm10                     8157
pm25                        0
relativehumidity            0
temperature                 0
um003                       0
temperature_2m              0
relative_humidity_2m        0
precipitation               0
surface_pressure            0
wind_speed_10m              0
wind_direction_10m          0
temperature_180m         9418
boundary_layer_height       0
dtype: int64

In [80]:
(df.isnull().sum()/(len(df)))*100

pm1                        0.000000
pm10                      86.610745
pm25                       0.000000
relativehumidity           0.000000
temperature                0.000000
um003                      0.000000
temperature_2m             0.000000
relative_humidity_2m       0.000000
precipitation              0.000000
surface_pressure           0.000000
wind_speed_10m             0.000000
wind_direction_10m         0.000000
temperature_180m         100.000000
boundary_layer_height      0.000000
dtype: float64

In [81]:
df = df.drop(columns=['pm10','temperature_180m'])

In [82]:
df.duplicated().sum()

np.int64(0)

In [83]:
df = df.asfreq('h')

df = df.interpolate(method='linear')

In [85]:
df.shape

(10735, 12)

In [86]:
df.to_csv('data/processed/hcmc_merged_cleaned.csv')